In [21]:
type(<phe.paillier.EncryptedNumber object at 0x000001FB87166790>)

SyntaxError: invalid syntax (1298308453.py, line 1)

In [22]:
from phe import paillier
public_key, private_key = paillier.generate_paillier_keypair()

In [23]:
type(<phe.paillier.EncryptedNumber object at 0x000001FB87166790>)

SyntaxError: invalid syntax (1298308453.py, line 1)

In [ ]:
type(phe.paillier.EncryptedNumber)

In [24]:
import numpy as np
arr = np.array([[1,2,3,4],
                [3,4,5,6],
                [7,8,9,0]
                ])

In [25]:
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [26]:
List = arr.tolist()

In [27]:
List

[[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 0]]

In [37]:
x = [] 
for i in range(len(List)):
    for j in range(4):
        x.append(List[i][j])     
        
        

In [41]:
x

array([1, 2, 3, 4, 3, 4, 5, 6, 7, 8, 9, 0])

In [40]:
x = np.array(x)
x.reshape(4,3)

array([[1, 2, 3],
       [4, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [ ]:
encrypted_number_X = [public_key.encrypt(x) for x in X_list[0]]